//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avocado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartament
    {
        public int ID { get; set; }
        public int HouseID { get; set; }
        public int Number { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<int> CountOfRooms { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<int> Floor { get; set; }
        public bool IsSold { get; set; }
        public decimal BuildingCost { get; set; }
        public Nullable<int> ApartmentValueAdded { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual House House { get; set; }
    }
}
